---
# Installs elasticsearch

- name: Starting elasticsearch role
  debug:
    msg: "{{ lookup('pipe','date') }}"

# Look for the shared_folder variable for Vagrant-based installs
- name: Look for Vagrant shared folder
  stat: path=/home/vagrant/shared/installers/
  register: shared_folder

- name: Default to installing elasticsearch
  set_fact:
    es_install_flag: true

- name: Get current elasticsearch version
  shell: curl -sS localhost:9200 | python -c 'import json, sys; print(json.loads(sys.stdin.read())["version"]["number"])'
  register: es_version_cmd
  ignore_errors: yes
  changed_when: false

- name: Set es_install_flag to false if es version is already installed
  set_fact:
    es_install_flag: false
  when: es_version_cmd.rc == 0 and (es_pkg_version == es_version_cmd.stdout)

- name: Look for existing elasticsearch Ubuntu repository
  stat: path="/etc/apt/sources.list.d/elasticsearch-2.x.list"
  register: es_repo_file
  when: es_install_flag == true

- name: Add elasticsearch repository, as needed
  apt_repository:
    repo: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
  when: es_install_flag == true and es_repo_file.stat.exists == false

- name: Update apt-cache if older than two hours
  apt:
    update_cache: yes
    cache_valid_time: 7200
  when: es_install_flag == true

# For Vagrant-managed environments
- include: install-from-shared-dir.yml
  when: shared_folder.stat.exists and es_install_flag == true and "vagrant_managed" in group_names

- name: Install elasticsearch
  apt:
    pkg: "{{ item }}"
    state: installed
    force: yes
  with_items:
    - elasticsearch

- name: Set elasticsearch to start at boot
  service:
    enabled: yes

- name: Update elasticsearch.yml config file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify:
    - Restart elasticsearch handler


- name: Finished with elasticsearch role
  debug:
    msg: "{{ lookup('pipe','date') }}"